/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppTeachersIndexRouteImport } from './routes/_app.teachers.index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app.students.index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppFeesIndexRouteImport } from './routes/_app.fees.index'
import { Route as AppTeachersAddRouteImport } from './routes/_app.teachers.add'
import { Route as AppStudentsAddRouteImport } from './routes/_app.students.add'
import { Route as AppStudentsClassKeyRouteImport } from './routes/_app.students.$classKey'
import { Route as AppFeesClassKeyRouteImport } from './routes/_app.fees.$classKey'
import { Route as AppPaymentsTeacherIdHistoryRouteImport } from './routes/_app.payments.$teacherId.history'
import { Route as AppFeesClassKeyStudentIdHistoryRouteImport } from './routes/_app.fees.$classKey.$studentId.history'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersIndexRoute = AppTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesIndexRoute = AppFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersAddRoute = AppTeachersAddRouteImport.update({
  id: '/teachers/add',
  path: '/teachers/add',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsAddRoute = AppStudentsAddRouteImport.update({
  id: '/students/add',
  path: '/students/add',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsClassKeyRoute = AppStudentsClassKeyRouteImport.update({
  id: '/students/$classKey',
  path: '/students/$classKey',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesClassKeyRoute = AppFeesClassKeyRouteImport.update({
  id: '/fees/$classKey',
  path: '/fees/$classKey',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsTeacherIdHistoryRoute =
  AppPaymentsTeacherIdHistoryRouteImport.update({
    id: '/payments/$teacherId/history',
    path: '/payments/$teacherId/history',
    getParentRoute: () => AppRoute,
  } as any)
const AppFeesClassKeyStudentIdHistoryRoute =
  AppFeesClassKeyStudentIdHistoryRouteImport.update({
    id: '/$studentId/history',
    path: '/$studentId/history',
    getParentRoute: () => AppFeesClassKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees/$classKey': typeof AppFeesClassKeyRouteWithChildren
  '/students/$classKey': typeof AppStudentsClassKeyRoute
  '/students/add': typeof AppStudentsAddRoute
  '/teachers/add': typeof AppTeachersAddRoute
  '/fees/': typeof AppFeesIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/teachers/': typeof AppTeachersIndexRoute
  '/payments/$teacherId/history': typeof AppPaymentsTeacherIdHistoryRoute
  '/fees/$classKey/$studentId/history': typeof AppFeesClassKeyStudentIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/fees/$classKey': typeof AppFeesClassKeyRouteWithChildren
  '/students/$classKey': typeof AppStudentsClassKeyRoute
  '/students/add': typeof AppStudentsAddRoute
  '/teachers/add': typeof AppTeachersAddRoute
  '/fees': typeof AppFeesIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/teachers': typeof AppTeachersIndexRoute
  '/payments/$teacherId/history': typeof AppPaymentsTeacherIdHistoryRoute
  '/fees/$classKey/$studentId/history': typeof AppFeesClassKeyStudentIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fees/$classKey': typeof AppFeesClassKeyRouteWithChildren
  '/_app/students/$classKey': typeof AppStudentsClassKeyRoute
  '/_app/students/add': typeof AppStudentsAddRoute
  '/_app/teachers/add': typeof AppTeachersAddRoute
  '/_app/fees/': typeof AppFeesIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/teachers/': typeof AppTeachersIndexRoute
  '/_app/payments/$teacherId/history': typeof AppPaymentsTeacherIdHistoryRoute
  '/_app/fees/$classKey/$studentId/history': typeof AppFeesClassKeyStudentIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/fees/$classKey'
    | '/students/$classKey'
    | '/students/add'
    | '/teachers/add'
    | '/fees/'
    | '/payments/'
    | '/students/'
    | '/teachers/'
    | '/payments/$teacherId/history'
    | '/fees/$classKey/$studentId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/fees/$classKey'
    | '/students/$classKey'
    | '/students/add'
    | '/teachers/add'
    | '/fees'
    | '/payments'
    | '/students'
    | '/teachers'
    | '/payments/$teacherId/history'
    | '/fees/$classKey/$studentId/history'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/fees/$classKey'
    | '/_app/students/$classKey'
    | '/_app/students/add'
    | '/_app/teachers/add'
    | '/_app/fees/'
    | '/_app/payments/'
    | '/_app/students/'
    | '/_app/teachers/'
    | '/_app/payments/$teacherId/history'
    | '/_app/fees/$classKey/$studentId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers/': {
      id: '/_app/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AppTeachersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/': {
      id: '/_app/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof AppFeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers/add': {
      id: '/_app/teachers/add'
      path: '/teachers/add'
      fullPath: '/teachers/add'
      preLoaderRoute: typeof AppTeachersAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/add': {
      id: '/_app/students/add'
      path: '/students/add'
      fullPath: '/students/add'
      preLoaderRoute: typeof AppStudentsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$classKey': {
      id: '/_app/students/$classKey'
      path: '/students/$classKey'
      fullPath: '/students/$classKey'
      preLoaderRoute: typeof AppStudentsClassKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/$classKey': {
      id: '/_app/fees/$classKey'
      path: '/fees/$classKey'
      fullPath: '/fees/$classKey'
      preLoaderRoute: typeof AppFeesClassKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$teacherId/history': {
      id: '/_app/payments/$teacherId/history'
      path: '/payments/$teacherId/history'
      fullPath: '/payments/$teacherId/history'
      preLoaderRoute: typeof AppPaymentsTeacherIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/$classKey/$studentId/history': {
      id: '/_app/fees/$classKey/$studentId/history'
      path: '/$studentId/history'
      fullPath: '/fees/$classKey/$studentId/history'
      preLoaderRoute: typeof AppFeesClassKeyStudentIdHistoryRouteImport
      parentRoute: typeof AppFeesClassKeyRoute
    }
  }
}

interface AppFeesClassKeyRouteChildren {
  AppFeesClassKeyStudentIdHistoryRoute: typeof AppFeesClassKeyStudentIdHistoryRoute
}

const AppFeesClassKeyRouteChildren: AppFeesClassKeyRouteChildren = {
  AppFeesClassKeyStudentIdHistoryRoute: AppFeesClassKeyStudentIdHistoryRoute,
}

const AppFeesClassKeyRouteWithChildren = AppFeesClassKeyRoute._addFileChildren(
  AppFeesClassKeyRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeesClassKeyRoute: typeof AppFeesClassKeyRouteWithChildren
  AppStudentsClassKeyRoute: typeof AppStudentsClassKeyRoute
  AppStudentsAddRoute: typeof AppStudentsAddRoute
  AppTeachersAddRoute: typeof AppTeachersAddRoute
  AppFeesIndexRoute: typeof AppFeesIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppTeachersIndexRoute: typeof AppTeachersIndexRoute
  AppPaymentsTeacherIdHistoryRoute: typeof AppPaymentsTeacherIdHistoryRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFeesClassKeyRoute: AppFeesClassKeyRouteWithChildren,
  AppStudentsClassKeyRoute: AppStudentsClassKeyRoute,
  AppStudentsAddRoute: AppStudentsAddRoute,
  AppTeachersAddRoute: AppTeachersAddRoute,
  AppFeesIndexRoute: AppFeesIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppTeachersIndexRoute: AppTeachersIndexRoute,
  AppPaymentsTeacherIdHistoryRoute: AppPaymentsTeacherIdHistoryRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
